
include ../../common/espia/include/espia.inc

CXXFLAGS = -I../include -I../../common/espia/include \
	   -I../../../hardware/include -I../../../common/include \
	   -I$(ESPIA_DRV_INCL) -Wall -pthread

all:		clean Frelon.o


clean:
	rm -f *.o
