#!/usr/bin/env python

import os, sys

def get_compat_os(target_dir, sub_dir=None):

    cs_path = ['/csadmin/local/scripts', '/csadmin/common/scripts']
    script_name = 'get_compat_os.share'
    for cs_dir in cs_path:
        script = cs_dir + '/' + script_name
        if os.path.exists(script):
            break
    else:
        raise 'Cannot find compat os'

    p = os.popen(script)
    compat_os = p.readline().strip()
    for os_name in compat_os.split():
        path = target_dir + '/' + os_name
        if sub_dir:
            path += '/' + sub_dir 
        if os.path.exists(path):
            return path

prog_name = os.path.basename(sys.argv[0])

this_dir = os.path.dirname(__file__)
server_dir = '%s/..' % this_dir
lib_dir = get_compat_os(server_dir, '/lib/' + prog_name)
sys.path.append(lib_dir)

from FrelonTacoCcd import FrelonServer

def main(argv):
    try:
        pers_name = argv[1]
    except:
        print 'Usage: %s <pers_name>' % prog_name
        sys.exit(1)

    server = FrelonServer(prog_name, pers_name)
    
if __name__ == '__main__':
    main(sys.argv)
    
