#!/usr/bin/env python

import os, sys
from FrelonTacoCcd import FrelonServer

def main(argv):
    prog_name = os.path.basename(argv[0])
    try:
        pers_name = argv[1]
    except:
        print 'Usage: %s <pers_name>' % prog_name
        sys.exit(1)

    server = FrelonServer(prog_name, pers_name)
    
if __name__ == '__main__':
    main(sys.argv)
    
