# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include:
    - applications/tango/python
    - camera/hamamatsu
    - camera/pco
    - camera/perkinelmer
    - camera/photonicscience
    - camera/princeton
    - camera/adsc
    - camera/advacam
    - camera/andor3
    - camera/aviex
    - camera/arinax
    - camera/dexela
    - camera/eiger
    - camera/mythen
    - camera/mythen3
    - camera/pilatus
    - camera/fli
    - camera/frelon
    - camera/imxpad
    - camera/lambda
    - camera/maxipix
    - camera/merlin
    - camera/pixirad
    - camera/pointgrey
    - camera/prosilica
    - camera/marccd
    - camera/rayonixhs
    - camera/slsdetector
    - camera/ueye
    - camera/ultra
    - camera/v4l2
    - camera/ximea
    - camera/xpad
    - camera/xspress3
    - camera/xh
    - camera/zwo
    - camera/andor
    - camera/basler
    - camera/dhyana
    - camera/iris
    - camera/roperscientific
    - camera/simulator

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt
