import os

try:
    Import('env')
except:
    env = Environment(CCFLAGS = '-fPIC')

env.Library('libControl',Glob('*.cpp') + Glob(os.path.join('..','software_operation','src','*.cpp')),
            LIBS = ['libControlSoftwareOperation'],
            LIBPATH = [os.path.join('..','software_operation','src')],
            CPPPATH = [os.path.join('..','include'),
                       os.path.join('..','..','common','include'),
                       os.path.join('..','..','hardware','include'),
                       os.path.join('..','software_operation','include'),
                       os.path.join('..','..','third-party','Processlib','core','include'),
                       os.path.join('..','..','third-party','Processlib','tasks','include'),
                       os.path.join('..','..','third-party','Sps','Include')])
