/*
 * Internal module API header file.
 *
 * Generated by SIP 4.10.2 on Mon Aug 22 11:23:58 2011
 */

#ifndef _limaadscAPI_H
#define _limaadscAPI_H


#include <sip.h>
#line 23 "../../common/sip/Debug.sip"
#include <Debug.h>
using namespace lima;
#line 16 "sipAPIlimaadsc.h"
#line 4 "limaadsc_tmp.sip"
extern "C" { void lima_import_array();}
#line 19 "sipAPIlimaadsc.h"

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_unregisterMaxImageSizeCallback 0
#define sipName_unregisterMaxImageSizeCallback &sipStrings_limaadsc[0]
#define sipNameNr_registerMaxImageSizeCallback 2
#define sipName_registerMaxImageSizeCallback &sipStrings_limaadsc[2]
#define sipNameNr_getNbHwAcquiredFrames 31
#define sipName_getNbHwAcquiredFrames &sipStrings_limaadsc[31]
#define sipNameNr_getDetectorImageSize 53
#define sipName_getDetectorImageSize &sipStrings_limaadsc[53]
#define sipNameNr_getNbAcquiredFrames 74
#define sipName_getNbAcquiredFrames &sipStrings_limaadsc[74]
#define sipNameNr_AdscCamera__Status 94
#define sipName_AdscCamera__Status &sipStrings_limaadsc[94]
#define sipNameNr_AdscDetInfoCtrlObj 113
#define sipName_AdscDetInfoCtrlObj &sipStrings_limaadsc[113]
#define sipNameNr_getDetectorModel 132
#define sipName_getDetectorModel &sipStrings_limaadsc[132]
#define sipNameNr_setCurrImageType 149
#define sipName_setCurrImageType &sipStrings_limaadsc[149]
#define sipNameNr_getCurrImageType 166
#define sipName_getCurrImageType &sipStrings_limaadsc[166]
#define sipNameNr_AdscHwInterface 183
#define sipName_AdscHwInterface &sipStrings_limaadsc[183]
#define sipNameNr_AdscSyncCtrlObj 199
#define sipName_AdscSyncCtrlObj &sipStrings_limaadsc[199]
#define sipNameNr_getDetectorType 215
#define sipName_getDetectorType &sipStrings_limaadsc[215]
#define sipNameNr_getDefImageType 231
#define sipName_getDefImageType &sipStrings_limaadsc[231]
#define sipNameNr_getMaxImageSize 247
#define sipName_getMaxImageSize &sipStrings_limaadsc[247]
#define sipNameNr_AdscBinCtrlObj 263
#define sipName_AdscBinCtrlObj &sipStrings_limaadsc[263]
#define sipNameNr_getValidRanges 278
#define sipName_getValidRanges &sipStrings_limaadsc[278]
#define sipNameNr_getNbHwFrames 293
#define sipName_getNbHwFrames &sipStrings_limaadsc[293]
#define sipNameNr_setNbHwFrames 307
#define sipName_setNbHwFrames &sipStrings_limaadsc[307]
#define sipNameNr_checkTrigMode 321
#define sipName_checkTrigMode &sipStrings_limaadsc[321]
#define sipNameNr_setLastImage 335
#define sipName_setLastImage &sipStrings_limaadsc[335]
#define sipNameNr_setImageKind 348
#define sipName_setImageKind &sipStrings_limaadsc[348]
#define sipNameNr_getBufferMgr 361
#define sipName_getBufferMgr &sipStrings_limaadsc[361]
#define sipNameNr_getPixelSize 374
#define sipName_getPixelSize &sipStrings_limaadsc[374]
#define sipNameNr_setFilename 387
#define sipName_setFilename &sipStrings_limaadsc[387]
#define sipNameNr_getNbFrames 399
#define sipName_getNbFrames &sipStrings_limaadsc[399]
#define sipNameNr_setNbFrames 411
#define sipName_setNbFrames &sipStrings_limaadsc[411]
#define sipNameNr_getTrigMode 423
#define sipName_getTrigMode &sipStrings_limaadsc[423]
#define sipNameNr_setTrigMode 435
#define sipName_setTrigMode &sipStrings_limaadsc[435]
#define sipNameNr_getFrameDim 447
#define sipName_getFrameDim &sipStrings_limaadsc[447]
#define sipNameNr_setFrameDim 459
#define sipName_setFrameDim &sipStrings_limaadsc[459]
#define sipNameNr_AdscCamera 471
#define sipName_AdscCamera &sipStrings_limaadsc[471]
#define sipNameNr_prepareAcq 482
#define sipName_prepareAcq &sipStrings_limaadsc[482]
#define sipNameNr_getCapList 493
#define sipName_getCapList &sipStrings_limaadsc[493]
#define sipNameNr_setAcqMode 504
#define sipName_setAcqMode &sipStrings_limaadsc[504]
#define sipNameNr_getLatTime 515
#define sipName_getLatTime &sipStrings_limaadsc[515]
#define sipNameNr_setLatTime 526
#define sipName_setLatTime &sipStrings_limaadsc[526]
#define sipNameNr_getExpTime 537
#define sipName_getExpTime &sipStrings_limaadsc[537]
#define sipNameNr_setExpTime 548
#define sipName_setExpTime &sipStrings_limaadsc[548]
#define sipNameNr_getStatus 559
#define sipName_getStatus &sipStrings_limaadsc[559]
#define sipNameNr_Exposure 569
#define sipName_Exposure &sipStrings_limaadsc[569]
#define sipNameNr_checkBin 578
#define sipName_checkBin &sipStrings_limaadsc[578]
#define sipNameNr_startAcq 587
#define sipName_startAcq &sipStrings_limaadsc[587]
#define sipNameNr___repr__ 596
#define sipName___repr__ &sipStrings_limaadsc[596]
#define sipNameNr_limaadsc 605
#define sipName_limaadsc &sipStrings_limaadsc[605]
#define sipNameNr_Latency 614
#define sipName_Latency &sipStrings_limaadsc[614]
#define sipNameNr_Readout 622
#define sipName_Readout &sipStrings_limaadsc[622]
#define sipNameNr_stopAcq 630
#define sipName_stopAcq &sipStrings_limaadsc[630]
#define sipNameNr_Status 106
#define sipName_Status &sipStrings_limaadsc[106]
#define sipNameNr_getBin 638
#define sipName_getBin &sipStrings_limaadsc[638]
#define sipNameNr_setBin 645
#define sipName_setBin &sipStrings_limaadsc[645]
#define sipNameNr_Ready 652
#define sipName_Ready &sipStrings_limaadsc[652]
#define sipNameNr_reset 658
#define sipName_reset &sipStrings_limaadsc[658]

#define sipMalloc                   sipAPI_limaadsc->api_malloc
#define sipFree                     sipAPI_limaadsc->api_free
#define sipBuildResult              sipAPI_limaadsc->api_build_result
#define sipCallMethod               sipAPI_limaadsc->api_call_method
#define sipParseResult              sipAPI_limaadsc->api_parse_result
#define sipParseArgs                sipAPI_limaadsc->api_parse_args
#define sipParseKwdArgs             sipAPI_limaadsc->api_parse_kwd_args
#define sipParsePair                sipAPI_limaadsc->api_parse_pair
#define sipCommonDtor               sipAPI_limaadsc->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_limaadsc->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_limaadsc->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_limaadsc->api_convert_to_void_ptr
#define sipAddException             sipAPI_limaadsc->api_add_exception
#define sipNoFunction               sipAPI_limaadsc->api_no_function
#define sipNoMethod                 sipAPI_limaadsc->api_no_method
#define sipAbstractMethod           sipAPI_limaadsc->api_abstract_method
#define sipBadClass                 sipAPI_limaadsc->api_bad_class
#define sipBadCatcherResult         sipAPI_limaadsc->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_limaadsc->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_limaadsc->api_bad_operator_arg
#define sipTrace                    sipAPI_limaadsc->api_trace
#define sipTransferBack             sipAPI_limaadsc->api_transfer_back
#define sipTransferTo               sipAPI_limaadsc->api_transfer_to
#define sipTransferBreak            sipAPI_limaadsc->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_limaadsc->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_limaadsc->api_wrapper_type
#define sipWrapperType_Type         sipAPI_limaadsc->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_limaadsc->api_voidptr_type
#define sipGetPyObject              sipAPI_limaadsc->api_get_pyobject
#define sipGetCppPtr                sipAPI_limaadsc->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_limaadsc->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_limaadsc->api_is_py_method
#define sipCallHook                 sipAPI_limaadsc->api_call_hook
#define sipStartThread              sipAPI_limaadsc->api_start_thread
#define sipEndThread                sipAPI_limaadsc->api_end_thread
#define sipConnectRx                sipAPI_limaadsc->api_connect_rx
#define sipDisconnectRx             sipAPI_limaadsc->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_limaadsc->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_limaadsc->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_limaadsc->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_limaadsc->api_add_type_instance
#define sipGetAddress               sipAPI_limaadsc->api_get_address
#define sipFreeSipslot              sipAPI_limaadsc->api_free_sipslot
#define sipSameSlot                 sipAPI_limaadsc->api_same_slot
#define sipPySlotExtend             sipAPI_limaadsc->api_pyslot_extend
#define sipConvertRx                sipAPI_limaadsc->api_convert_rx
#define sipAddDelayedDtor           sipAPI_limaadsc->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_limaadsc->api_can_convert_to_type
#define sipConvertToType            sipAPI_limaadsc->api_convert_to_type
#define sipForceConvertToType       sipAPI_limaadsc->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_limaadsc->api_can_convert_to_enum
#define sipReleaseType              sipAPI_limaadsc->api_release_type
#define sipConvertFromType          sipAPI_limaadsc->api_convert_from_type
#define sipConvertFromNewType       sipAPI_limaadsc->api_convert_from_new_type
#define sipConvertFromEnum          sipAPI_limaadsc->api_convert_from_enum
#define sipGetState                 sipAPI_limaadsc->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_limaadsc->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_limaadsc->api_export_symbol
#define sipImportSymbol             sipAPI_limaadsc->api_import_symbol
#define sipFindType                 sipAPI_limaadsc->api_find_type
#define sipFindNamedEnum            sipAPI_limaadsc->api_find_named_enum
#define sipBytes_AsChar             sipAPI_limaadsc->api_bytes_as_char
#define sipBytes_AsString           sipAPI_limaadsc->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_limaadsc->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_limaadsc->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_limaadsc->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_limaadsc->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_limaadsc->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_limaadsc->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_limaadsc->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_limaadsc->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_limaadsc->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_limaadsc->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_limaadsc->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_limaadsc->api_invoke_slot
#define sipSaveSlot                 sipAPI_limaadsc->api_save_slot
#define sipClearAnySlotReference    sipAPI_limaadsc->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_limaadsc->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_limaadsc->api_deprecated
#define sipKeepReference            sipAPI_limaadsc->api_keep_reference
#define sipRegisterPyType           sipAPI_limaadsc->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_limaadsc->api_type_from_py_type_object
#define sipTypeScope                sipAPI_limaadsc->api_type_scope
#define sipResolveTypedef           sipAPI_limaadsc->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_limaadsc->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_limaadsc->api_is_api_enabled
#define sipExportModule             sipAPI_limaadsc->api_export_module
#define sipInitModule               sipAPI_limaadsc->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_limaadsc->api_map_string_to_class
#define sipMapIntToClass            sipAPI_limaadsc->api_map_int_to_class
#define sipFindClass                sipAPI_limaadsc->api_find_class
#define sipFindMappedType           sipAPI_limaadsc->api_find_mapped_type
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_limaadsc->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_limaadsc[];

#define sipType_SoftOpId              sipModuleAPI_limaadsc_limacore->em_types[97]
#define sipEnum_SoftOpId              sipModuleAPI_limaadsc_limacore->em_types[97]->u.td_py_type
#define sipType_YBorder              sipModuleAPI_limaadsc_limacore->em_types[108]
#define sipEnum_YBorder              sipModuleAPI_limaadsc_limacore->em_types[108]->u.td_py_type
#define sipType_XBorder              sipModuleAPI_limaadsc_limacore->em_types[107]
#define sipEnum_XBorder              sipModuleAPI_limaadsc_limacore->em_types[107]->u.td_py_type
#define sipType_ErrorType              sipModuleAPI_limaadsc_limacore->em_types[50]
#define sipEnum_ErrorType              sipModuleAPI_limaadsc_limacore->em_types[50]->u.td_py_type
#define sipType_Layer              sipModuleAPI_limaadsc_limacore->em_types[80]
#define sipEnum_Layer              sipModuleAPI_limaadsc_limacore->em_types[80]->u.td_py_type
#define sipType_DebModule              sipModuleAPI_limaadsc_limacore->em_types[45]
#define sipEnum_DebModule              sipModuleAPI_limaadsc_limacore->em_types[45]->u.td_py_type
#define sipType_DebFormat              sipModuleAPI_limaadsc_limacore->em_types[44]
#define sipEnum_DebFormat              sipModuleAPI_limaadsc_limacore->em_types[44]->u.td_py_type
#define sipType_DebType              sipModuleAPI_limaadsc_limacore->em_types[48]
#define sipEnum_DebType              sipModuleAPI_limaadsc_limacore->em_types[48]->u.td_py_type
#define sipType_RotationMode              sipModuleAPI_limaadsc_limacore->em_types[86]
#define sipEnum_RotationMode              sipModuleAPI_limaadsc_limacore->em_types[86]->u.td_py_type
#define sipType_VideoMode              sipModuleAPI_limaadsc_limacore->em_types[106]
#define sipEnum_VideoMode              sipModuleAPI_limaadsc_limacore->em_types[106]->u.td_py_type
#define sipType_DetStatus              sipModuleAPI_limaadsc_limacore->em_types[49]
#define sipEnum_DetStatus              sipModuleAPI_limaadsc_limacore->em_types[49]->u.td_py_type
#define sipType_AcqStatus              sipModuleAPI_limaadsc_limacore->em_types[3]
#define sipEnum_AcqStatus              sipModuleAPI_limaadsc_limacore->em_types[3]->u.td_py_type
#define sipType_ShutterMode              sipModuleAPI_limaadsc_limacore->em_types[87]
#define sipEnum_ShutterMode              sipModuleAPI_limaadsc_limacore->em_types[87]->u.td_py_type
#define sipType_BufferMode              sipModuleAPI_limaadsc_limacore->em_types[11]
#define sipEnum_BufferMode              sipModuleAPI_limaadsc_limacore->em_types[11]->u.td_py_type
#define sipType_TrigMode              sipModuleAPI_limaadsc_limacore->em_types[105]
#define sipEnum_TrigMode              sipModuleAPI_limaadsc_limacore->em_types[105]->u.td_py_type
#define sipType_AcqMode              sipModuleAPI_limaadsc_limacore->em_types[0]
#define sipEnum_AcqMode              sipModuleAPI_limaadsc_limacore->em_types[0]->u.td_py_type
#define sipType_ImageType              sipModuleAPI_limaadsc_limacore->em_types[79]
#define sipEnum_ImageType              sipModuleAPI_limaadsc_limacore->em_types[79]->u.td_py_type
#define sipType_AlignDir              sipModuleAPI_limaadsc_limacore->em_types[4]
#define sipEnum_AlignDir              sipModuleAPI_limaadsc_limacore->em_types[4]->u.td_py_type

#define sipType_AdscDetInfoCtrlObj              sipModuleAPI_limaadsc.em_types[3]
#define sipClass_AdscDetInfoCtrlObj             sipModuleAPI_limaadsc.em_types[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_limaadsc_AdscDetInfoCtrlObj;

#define sipType_AdscSyncCtrlObj              sipModuleAPI_limaadsc.em_types[5]
#define sipClass_AdscSyncCtrlObj             sipModuleAPI_limaadsc.em_types[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_limaadsc_AdscSyncCtrlObj;

#define sipType_AdscBinCtrlObj              sipModuleAPI_limaadsc.em_types[0]
#define sipClass_AdscBinCtrlObj             sipModuleAPI_limaadsc.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_limaadsc_AdscBinCtrlObj;

#define sipType_AdscHwInterface              sipModuleAPI_limaadsc.em_types[4]
#define sipClass_AdscHwInterface             sipModuleAPI_limaadsc.em_types[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_limaadsc_AdscHwInterface;

#define sipType_AdscCamera              sipModuleAPI_limaadsc.em_types[1]
#define sipClass_AdscCamera             sipModuleAPI_limaadsc.em_types[1]->u.td_wrapper_type

#define sipType_AdscCamera_Status              sipModuleAPI_limaadsc.em_types[2]
#define sipEnum_AdscCamera_Status              sipModuleAPI_limaadsc.em_types[2]->u.td_py_type

extern sipClassTypeDef sipTypeDef_limaadsc_AdscCamera;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_limaadsc;
extern sipExportedModuleDef sipModuleAPI_limaadsc;

#define sipType_Data_HeaderContainer_itemIterator              sipModuleAPI_limaadsc_processlib->em_types[2]
#define sipClass_Data_HeaderContainer_itemIterator             sipModuleAPI_limaadsc_processlib->em_types[2]->u.td_wrapper_type

#define sipType_Data              sipModuleAPI_limaadsc_processlib->em_types[0]
#define sipClass_Data             sipModuleAPI_limaadsc_processlib->em_types[0]->u.td_wrapper_type

#define sipType_Data_HeaderContainer              sipModuleAPI_limaadsc_processlib->em_types[1]
#define sipClass_Data_HeaderContainer             sipModuleAPI_limaadsc_processlib->em_types[1]->u.td_wrapper_type

#define sipType_TaskEventCallback              sipModuleAPI_limaadsc_processlib->em_types[6]
#define sipClass_TaskEventCallback             sipModuleAPI_limaadsc_processlib->em_types[6]->u.td_wrapper_type

#define sipType_LinkTask              sipModuleAPI_limaadsc_processlib->em_types[3]
#define sipClass_LinkTask             sipModuleAPI_limaadsc_processlib->em_types[3]->u.td_wrapper_type

#define sipType_SinkTaskBase              sipModuleAPI_limaadsc_processlib->em_types[5]
#define sipClass_SinkTaskBase             sipModuleAPI_limaadsc_processlib->em_types[5]->u.td_wrapper_type

#define sipType_TaskMgr              sipModuleAPI_limaadsc_processlib->em_types[7]
#define sipClass_TaskMgr             sipModuleAPI_limaadsc_processlib->em_types[7]->u.td_wrapper_type

#define sipType_PoolThreadMgr              sipModuleAPI_limaadsc_processlib->em_types[4]
#define sipClass_PoolThreadMgr             sipModuleAPI_limaadsc_processlib->em_types[4]->u.td_wrapper_type

#if !defined(sipType_Tasks)
#define sipType_Tasks              sipModuleAPI_limaadsc_processlib->em_types[8]
#define sipClass_Tasks             sipModuleAPI_limaadsc_processlib->em_types[8]->u.td_wrapper_type
#endif

#define sipType_Tasks_BpmManager              sipModuleAPI_limaadsc_processlib->em_types[11]
#define sipClass_Tasks_BpmManager             sipModuleAPI_limaadsc_processlib->em_types[11]->u.td_wrapper_type

#define sipType_Tasks_BpmManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[13]
#define sipEnum_Tasks_BpmManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[13]->u.td_py_type
#define sipType_Tasks_BpmManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[12]
#define sipEnum_Tasks_BpmManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[12]->u.td_py_type

#define sipType_Tasks_BpmResult              sipModuleAPI_limaadsc_processlib->em_types[14]
#define sipClass_Tasks_BpmResult             sipModuleAPI_limaadsc_processlib->em_types[14]->u.td_wrapper_type

#define sipType_Tasks_BpmTask              sipModuleAPI_limaadsc_processlib->em_types[15]
#define sipClass_Tasks_BpmTask             sipModuleAPI_limaadsc_processlib->em_types[15]->u.td_wrapper_type

#define sipType_Tasks_FlatfieldCorrection              sipModuleAPI_limaadsc_processlib->em_types[16]
#define sipClass_Tasks_FlatfieldCorrection             sipModuleAPI_limaadsc_processlib->em_types[16]->u.td_wrapper_type

#define sipType_Tasks_Mask              sipModuleAPI_limaadsc_processlib->em_types[19]
#define sipClass_Tasks_Mask             sipModuleAPI_limaadsc_processlib->em_types[19]->u.td_wrapper_type

#define sipType_Tasks_Roi2SpectrumManager              sipModuleAPI_limaadsc_processlib->em_types[20]
#define sipClass_Tasks_Roi2SpectrumManager             sipModuleAPI_limaadsc_processlib->em_types[20]->u.td_wrapper_type

#define sipType_Tasks_Roi2SpectrumManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[22]
#define sipEnum_Tasks_Roi2SpectrumManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[22]->u.td_py_type
#define sipType_Tasks_Roi2SpectrumManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[21]
#define sipEnum_Tasks_Roi2SpectrumManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[21]->u.td_py_type

#define sipType_Tasks_Roi2SpectrumResult              sipModuleAPI_limaadsc_processlib->em_types[23]
#define sipClass_Tasks_Roi2SpectrumResult             sipModuleAPI_limaadsc_processlib->em_types[23]->u.td_wrapper_type

#define sipType_Tasks_Roi2SpectrumTask              sipModuleAPI_limaadsc_processlib->em_types[24]
#define sipClass_Tasks_Roi2SpectrumTask             sipModuleAPI_limaadsc_processlib->em_types[24]->u.td_wrapper_type

#define sipType_Tasks_Roi2SpectrumTask_Mode              sipModuleAPI_limaadsc_processlib->em_types[25]
#define sipEnum_Tasks_Roi2SpectrumTask_Mode              sipModuleAPI_limaadsc_processlib->em_types[25]->u.td_py_type

#define sipType_Tasks_Flip              sipModuleAPI_limaadsc_processlib->em_types[17]
#define sipClass_Tasks_Flip             sipModuleAPI_limaadsc_processlib->em_types[17]->u.td_wrapper_type

#define sipType_Tasks_Flip_FLIP_MODE              sipModuleAPI_limaadsc_processlib->em_types[18]
#define sipEnum_Tasks_Flip_FLIP_MODE              sipModuleAPI_limaadsc_processlib->em_types[18]->u.td_py_type

#define sipType_Tasks_SoftRoi              sipModuleAPI_limaadsc_processlib->em_types[33]
#define sipClass_Tasks_SoftRoi             sipModuleAPI_limaadsc_processlib->em_types[33]->u.td_wrapper_type

#define sipType_Tasks_Rotation              sipModuleAPI_limaadsc_processlib->em_types[31]
#define sipClass_Tasks_Rotation             sipModuleAPI_limaadsc_processlib->em_types[31]->u.td_wrapper_type

#define sipType_Tasks_Rotation_Type              sipModuleAPI_limaadsc_processlib->em_types[32]
#define sipEnum_Tasks_Rotation_Type              sipModuleAPI_limaadsc_processlib->em_types[32]->u.td_py_type

#define sipType_Tasks_RoiCounterManager              sipModuleAPI_limaadsc_processlib->em_types[26]
#define sipClass_Tasks_RoiCounterManager             sipModuleAPI_limaadsc_processlib->em_types[26]->u.td_wrapper_type

#define sipType_Tasks_RoiCounterManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[28]
#define sipEnum_Tasks_RoiCounterManager_RUN_MODE              sipModuleAPI_limaadsc_processlib->em_types[28]->u.td_py_type
#define sipType_Tasks_RoiCounterManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[27]
#define sipEnum_Tasks_RoiCounterManager_ErrorCode              sipModuleAPI_limaadsc_processlib->em_types[27]->u.td_py_type

#define sipType_Tasks_RoiCounterResult              sipModuleAPI_limaadsc_processlib->em_types[29]
#define sipClass_Tasks_RoiCounterResult             sipModuleAPI_limaadsc_processlib->em_types[29]->u.td_wrapper_type

#define sipType_Tasks_RoiCounterTask              sipModuleAPI_limaadsc_processlib->em_types[30]
#define sipClass_Tasks_RoiCounterTask             sipModuleAPI_limaadsc_processlib->em_types[30]->u.td_wrapper_type

#define sipType_Tasks_Binning              sipModuleAPI_limaadsc_processlib->em_types[10]
#define sipClass_Tasks_Binning             sipModuleAPI_limaadsc_processlib->em_types[10]->u.td_wrapper_type

#define sipType_Tasks_BackgroundSubstraction              sipModuleAPI_limaadsc_processlib->em_types[9]
#define sipClass_Tasks_BackgroundSubstraction             sipModuleAPI_limaadsc_processlib->em_types[9]->u.td_wrapper_type
extern const sipExportedModuleDef *sipModuleAPI_limaadsc_processlib;

#define sipType_Timestamp              sipModuleAPI_limaadsc_limacore->em_types[104]
#define sipClass_Timestamp             sipModuleAPI_limaadsc_limacore->em_types[104]->u.td_wrapper_type

#define sipType_DebParams              sipModuleAPI_limaadsc_limacore->em_types[47]
#define sipClass_DebParams             sipModuleAPI_limaadsc_limacore->em_types[47]->u.td_wrapper_type

#define sipType_DebObj              sipModuleAPI_limaadsc_limacore->em_types[46]
#define sipClass_DebObj             sipModuleAPI_limaadsc_limacore->em_types[46]->u.td_wrapper_type

#define sipType_AcqState              sipModuleAPI_limaadsc_limacore->em_types[1]
#define sipClass_AcqState             sipModuleAPI_limaadsc_limacore->em_types[1]->u.td_wrapper_type

#define sipType_AcqState_State              sipModuleAPI_limaadsc_limacore->em_types[2]
#define sipEnum_AcqState_State              sipModuleAPI_limaadsc_limacore->em_types[2]->u.td_py_type

#define sipType_MutexAttr              sipModuleAPI_limaadsc_limacore->em_types[82]
#define sipClass_MutexAttr             sipModuleAPI_limaadsc_limacore->em_types[82]->u.td_wrapper_type

#define sipType_MutexAttr_Type              sipModuleAPI_limaadsc_limacore->em_types[83]
#define sipEnum_MutexAttr_Type              sipModuleAPI_limaadsc_limacore->em_types[83]->u.td_py_type

#define sipType_Mutex              sipModuleAPI_limaadsc_limacore->em_types[81]
#define sipClass_Mutex             sipModuleAPI_limaadsc_limacore->em_types[81]->u.td_wrapper_type

#define sipType_Cond              sipModuleAPI_limaadsc_limacore->em_types[12]
#define sipClass_Cond             sipModuleAPI_limaadsc_limacore->em_types[12]->u.td_wrapper_type

#define sipType_Point              sipModuleAPI_limaadsc_limacore->em_types[84]
#define sipClass_Point             sipModuleAPI_limaadsc_limacore->em_types[84]->u.td_wrapper_type

#define sipType_Corner              sipModuleAPI_limaadsc_limacore->em_types[13]
#define sipClass_Corner             sipModuleAPI_limaadsc_limacore->em_types[13]->u.td_wrapper_type

#define sipType_Size              sipModuleAPI_limaadsc_limacore->em_types[89]
#define sipClass_Size             sipModuleAPI_limaadsc_limacore->em_types[89]->u.td_wrapper_type

#define sipType_Bin              sipModuleAPI_limaadsc_limacore->em_types[5]
#define sipClass_Bin             sipModuleAPI_limaadsc_limacore->em_types[5]->u.td_wrapper_type

#define sipType_Flip              sipModuleAPI_limaadsc_limacore->em_types[51]
#define sipClass_Flip             sipModuleAPI_limaadsc_limacore->em_types[51]->u.td_wrapper_type

#define sipType_Roi              sipModuleAPI_limaadsc_limacore->em_types[85]
#define sipClass_Roi             sipModuleAPI_limaadsc_limacore->em_types[85]->u.td_wrapper_type

#define sipType_FrameDim              sipModuleAPI_limaadsc_limacore->em_types[52]
#define sipClass_FrameDim             sipModuleAPI_limaadsc_limacore->em_types[52]->u.td_wrapper_type

#define sipType_HwFlipCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[62]
#define sipClass_HwFlipCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[62]->u.td_wrapper_type

#define sipType_HwBufferCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[56]
#define sipClass_HwBufferCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[56]->u.td_wrapper_type

#define sipType_HwRoiCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[72]
#define sipClass_HwRoiCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[72]->u.td_wrapper_type

#define sipType_HwSyncCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[76]
#define sipClass_HwSyncCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[76]->u.td_wrapper_type

#define sipType_HwSyncCtrlObj_ValidRangesType              sipModuleAPI_limaadsc_limacore->em_types[78]
#define sipClass_HwSyncCtrlObj_ValidRangesType             sipModuleAPI_limaadsc_limacore->em_types[78]->u.td_wrapper_type

#define sipType_HwSyncCtrlObj_ValidRangesCallback              sipModuleAPI_limaadsc_limacore->em_types[77]
#define sipClass_HwSyncCtrlObj_ValidRangesCallback             sipModuleAPI_limaadsc_limacore->em_types[77]->u.td_wrapper_type

#define sipType_HwShutterCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[75]
#define sipClass_HwShutterCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[75]->u.td_wrapper_type

#define sipType_HwFrameCallbackGen              sipModuleAPI_limaadsc_limacore->em_types[64]
#define sipClass_HwFrameCallbackGen             sipModuleAPI_limaadsc_limacore->em_types[64]->u.td_wrapper_type

#define sipType_HwFrameCallback              sipModuleAPI_limaadsc_limacore->em_types[63]
#define sipClass_HwFrameCallback             sipModuleAPI_limaadsc_limacore->em_types[63]->u.td_wrapper_type

#define sipType_HwBufferSave              sipModuleAPI_limaadsc_limacore->em_types[57]
#define sipClass_HwBufferSave             sipModuleAPI_limaadsc_limacore->em_types[57]->u.td_wrapper_type

#define sipType_HwBufferSave_FileFormat              sipModuleAPI_limaadsc_limacore->em_types[58]
#define sipEnum_HwBufferSave_FileFormat              sipModuleAPI_limaadsc_limacore->em_types[58]->u.td_py_type

#define sipType_BufferAllocMgr              sipModuleAPI_limaadsc_limacore->em_types[6]
#define sipClass_BufferAllocMgr             sipModuleAPI_limaadsc_limacore->em_types[6]->u.td_wrapper_type

#define sipType_SoftBufferAllocMgr              sipModuleAPI_limaadsc_limacore->em_types[90]
#define sipClass_SoftBufferAllocMgr             sipModuleAPI_limaadsc_limacore->em_types[90]->u.td_wrapper_type

#define sipType_BufferCbMgr              sipModuleAPI_limaadsc_limacore->em_types[7]
#define sipClass_BufferCbMgr             sipModuleAPI_limaadsc_limacore->em_types[7]->u.td_wrapper_type

#define sipType_BufferCbMgr_Cap              sipModuleAPI_limaadsc_limacore->em_types[8]
#define sipEnum_BufferCbMgr_Cap              sipModuleAPI_limaadsc_limacore->em_types[8]->u.td_py_type

#define sipType_StdBufferCbMgr              sipModuleAPI_limaadsc_limacore->em_types[103]
#define sipClass_StdBufferCbMgr             sipModuleAPI_limaadsc_limacore->em_types[103]->u.td_wrapper_type

#define sipType_BufferCtrlMgr              sipModuleAPI_limaadsc_limacore->em_types[9]
#define sipClass_BufferCtrlMgr             sipModuleAPI_limaadsc_limacore->em_types[9]->u.td_wrapper_type

#define sipType_BufferCtrlMgr_AcqMode              sipModuleAPI_limaadsc_limacore->em_types[10]
#define sipEnum_BufferCtrlMgr_AcqMode              sipModuleAPI_limaadsc_limacore->em_types[10]->u.td_py_type

#define sipType_HwFrameInfoType              sipModuleAPI_limaadsc_limacore->em_types[65]
#define sipClass_HwFrameInfoType             sipModuleAPI_limaadsc_limacore->em_types[65]->u.td_wrapper_type

#define sipType_HwFrameInfoType_OwnerShip              sipModuleAPI_limaadsc_limacore->em_types[66]
#define sipEnum_HwFrameInfoType_OwnerShip              sipModuleAPI_limaadsc_limacore->em_types[66]->u.td_py_type

#define sipType_HwMaxImageSizeCallback              sipModuleAPI_limaadsc_limacore->em_types[70]
#define sipClass_HwMaxImageSizeCallback             sipModuleAPI_limaadsc_limacore->em_types[70]->u.td_wrapper_type

#define sipType_HwMaxImageSizeCallbackGen              sipModuleAPI_limaadsc_limacore->em_types[71]
#define sipClass_HwMaxImageSizeCallbackGen             sipModuleAPI_limaadsc_limacore->em_types[71]->u.td_wrapper_type

#define sipType_HwInterface              sipModuleAPI_limaadsc_limacore->em_types[67]
#define sipClass_HwInterface             sipModuleAPI_limaadsc_limacore->em_types[67]->u.td_wrapper_type

#define sipType_HwInterface_ResetLevel              sipModuleAPI_limaadsc_limacore->em_types[68]
#define sipEnum_HwInterface_ResetLevel              sipModuleAPI_limaadsc_limacore->em_types[68]->u.td_py_type

#define sipType_HwInterface_StatusType              sipModuleAPI_limaadsc_limacore->em_types[69]
#define sipClass_HwInterface_StatusType             sipModuleAPI_limaadsc_limacore->em_types[69]->u.td_wrapper_type

#define sipType_HwCap              sipModuleAPI_limaadsc_limacore->em_types[59]
#define sipClass_HwCap             sipModuleAPI_limaadsc_limacore->em_types[59]->u.td_wrapper_type

#define sipType_HwCap_Type              sipModuleAPI_limaadsc_limacore->em_types[60]
#define sipEnum_HwCap_Type              sipModuleAPI_limaadsc_limacore->em_types[60]->u.td_py_type

#define sipType_HwSerialLine              sipModuleAPI_limaadsc_limacore->em_types[73]
#define sipClass_HwSerialLine             sipModuleAPI_limaadsc_limacore->em_types[73]->u.td_wrapper_type

#define sipType_HwSerialLine_TimeoutConst              sipModuleAPI_limaadsc_limacore->em_types[74]
#define sipEnum_HwSerialLine_TimeoutConst              sipModuleAPI_limaadsc_limacore->em_types[74]->u.td_py_type

#define sipType_HwDetInfoCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[61]
#define sipClass_HwDetInfoCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[61]->u.td_wrapper_type

#define sipType_HwBinCtrlObj              sipModuleAPI_limaadsc_limacore->em_types[55]
#define sipClass_HwBinCtrlObj             sipModuleAPI_limaadsc_limacore->em_types[55]->u.td_wrapper_type

#define sipType_SoftOpExternalMgr              sipModuleAPI_limaadsc_limacore->em_types[94]
#define sipClass_SoftOpExternalMgr             sipModuleAPI_limaadsc_limacore->em_types[94]->u.td_wrapper_type

#define sipType_SoftOpKey              sipModuleAPI_limaadsc_limacore->em_types[98]
#define sipClass_SoftOpKey             sipModuleAPI_limaadsc_limacore->em_types[98]->u.td_wrapper_type

#define sipType_SoftOpBackgroundSubstraction              sipModuleAPI_limaadsc_limacore->em_types[91]
#define sipClass_SoftOpBackgroundSubstraction             sipModuleAPI_limaadsc_limacore->em_types[91]->u.td_wrapper_type

#define sipType_SoftOpBinning              sipModuleAPI_limaadsc_limacore->em_types[92]
#define sipClass_SoftOpBinning             sipModuleAPI_limaadsc_limacore->em_types[92]->u.td_wrapper_type

#define sipType_SoftOpBpm              sipModuleAPI_limaadsc_limacore->em_types[93]
#define sipClass_SoftOpBpm             sipModuleAPI_limaadsc_limacore->em_types[93]->u.td_wrapper_type

#define sipType_SoftOpFlatfieldCorrection              sipModuleAPI_limaadsc_limacore->em_types[95]
#define sipClass_SoftOpFlatfieldCorrection             sipModuleAPI_limaadsc_limacore->em_types[95]->u.td_wrapper_type

#define sipType_SoftOpFlip              sipModuleAPI_limaadsc_limacore->em_types[96]
#define sipClass_SoftOpFlip             sipModuleAPI_limaadsc_limacore->em_types[96]->u.td_wrapper_type

#define sipType_SoftOpMask              sipModuleAPI_limaadsc_limacore->em_types[99]
#define sipClass_SoftOpMask             sipModuleAPI_limaadsc_limacore->em_types[99]->u.td_wrapper_type

#define sipType_SoftOpRoiCounter              sipModuleAPI_limaadsc_limacore->em_types[101]
#define sipClass_SoftOpRoiCounter             sipModuleAPI_limaadsc_limacore->em_types[101]->u.td_wrapper_type

#define sipType_SoftOpRoi2Spectrum              sipModuleAPI_limaadsc_limacore->em_types[100]
#define sipClass_SoftOpRoi2Spectrum             sipModuleAPI_limaadsc_limacore->em_types[100]->u.td_wrapper_type

#define sipType_SoftOpSoftRoi              sipModuleAPI_limaadsc_limacore->em_types[102]
#define sipClass_SoftOpSoftRoi             sipModuleAPI_limaadsc_limacore->em_types[102]->u.td_wrapper_type

#define sipType_CtBuffer              sipModuleAPI_limaadsc_limacore->em_types[20]
#define sipClass_CtBuffer             sipModuleAPI_limaadsc_limacore->em_types[20]->u.td_wrapper_type

#define sipType_CtBuffer_Parameters              sipModuleAPI_limaadsc_limacore->em_types[21]
#define sipClass_CtBuffer_Parameters             sipModuleAPI_limaadsc_limacore->em_types[21]->u.td_wrapper_type

#define sipType_CtVideo              sipModuleAPI_limaadsc_limacore->em_types[40]
#define sipClass_CtVideo             sipModuleAPI_limaadsc_limacore->em_types[40]->u.td_wrapper_type

#define sipType_CtVideo_Parameters              sipModuleAPI_limaadsc_limacore->em_types[43]
#define sipClass_CtVideo_Parameters             sipModuleAPI_limaadsc_limacore->em_types[43]->u.td_wrapper_type

#define sipType_CtVideo_Image              sipModuleAPI_limaadsc_limacore->em_types[41]
#define sipClass_CtVideo_Image             sipModuleAPI_limaadsc_limacore->em_types[41]->u.td_wrapper_type

#define sipType_CtVideo_ImageCallback              sipModuleAPI_limaadsc_limacore->em_types[42]
#define sipClass_CtVideo_ImageCallback             sipModuleAPI_limaadsc_limacore->em_types[42]->u.td_wrapper_type

#define sipType_CtSwBinRoiFlip              sipModuleAPI_limaadsc_limacore->em_types[39]
#define sipClass_CtSwBinRoiFlip             sipModuleAPI_limaadsc_limacore->em_types[39]->u.td_wrapper_type

#define sipType_CtHwBinRoiFlip              sipModuleAPI_limaadsc_limacore->em_types[29]
#define sipClass_CtHwBinRoiFlip             sipModuleAPI_limaadsc_limacore->em_types[29]->u.td_wrapper_type

#define sipType_CtImage              sipModuleAPI_limaadsc_limacore->em_types[30]
#define sipClass_CtImage             sipModuleAPI_limaadsc_limacore->em_types[30]->u.td_wrapper_type

#define sipType_CtImage_ImageOpMode              sipModuleAPI_limaadsc_limacore->em_types[31]
#define sipEnum_CtImage_ImageOpMode              sipModuleAPI_limaadsc_limacore->em_types[31]->u.td_py_type

#define sipType_CtShutter              sipModuleAPI_limaadsc_limacore->em_types[37]
#define sipClass_CtShutter             sipModuleAPI_limaadsc_limacore->em_types[37]->u.td_wrapper_type

#define sipType_CtSaving              sipModuleAPI_limaadsc_limacore->em_types[32]
#define sipClass_CtSaving             sipModuleAPI_limaadsc_limacore->em_types[32]->u.td_wrapper_type

#define sipType_CtSaving_OverwritePolicy              sipModuleAPI_limaadsc_limacore->em_types[34]
#define sipEnum_CtSaving_OverwritePolicy              sipModuleAPI_limaadsc_limacore->em_types[34]->u.td_py_type
#define sipType_CtSaving_SavingMode              sipModuleAPI_limaadsc_limacore->em_types[36]
#define sipEnum_CtSaving_SavingMode              sipModuleAPI_limaadsc_limacore->em_types[36]->u.td_py_type
#define sipType_CtSaving_FileFormat              sipModuleAPI_limaadsc_limacore->em_types[33]
#define sipEnum_CtSaving_FileFormat              sipModuleAPI_limaadsc_limacore->em_types[33]->u.td_py_type

#define sipType_CtSaving_Parameters              sipModuleAPI_limaadsc_limacore->em_types[35]
#define sipClass_CtSaving_Parameters             sipModuleAPI_limaadsc_limacore->em_types[35]->u.td_wrapper_type

#define sipType_CtAcquisition              sipModuleAPI_limaadsc_limacore->em_types[17]
#define sipClass_CtAcquisition             sipModuleAPI_limaadsc_limacore->em_types[17]->u.td_wrapper_type

#define sipType_CtAcquisition_AccTimeMode              sipModuleAPI_limaadsc_limacore->em_types[18]
#define sipEnum_CtAcquisition_AccTimeMode              sipModuleAPI_limaadsc_limacore->em_types[18]->u.td_py_type

#define sipType_CtAcquisition_Parameters              sipModuleAPI_limaadsc_limacore->em_types[19]
#define sipClass_CtAcquisition_Parameters             sipModuleAPI_limaadsc_limacore->em_types[19]->u.td_wrapper_type

#define sipType_CtAccumulation              sipModuleAPI_limaadsc_limacore->em_types[14]
#define sipClass_CtAccumulation             sipModuleAPI_limaadsc_limacore->em_types[14]->u.td_wrapper_type

#define sipType_CtAccumulation_Parameters              sipModuleAPI_limaadsc_limacore->em_types[15]
#define sipClass_CtAccumulation_Parameters             sipModuleAPI_limaadsc_limacore->em_types[15]->u.td_wrapper_type

#define sipType_CtAccumulation_ThresholdCallback              sipModuleAPI_limaadsc_limacore->em_types[16]
#define sipClass_CtAccumulation_ThresholdCallback             sipModuleAPI_limaadsc_limacore->em_types[16]->u.td_wrapper_type

#define sipType_CtControl              sipModuleAPI_limaadsc_limacore->em_types[22]
#define sipClass_CtControl             sipModuleAPI_limaadsc_limacore->em_types[22]->u.td_wrapper_type

#define sipType_CtControl_CameraErrorCode              sipModuleAPI_limaadsc_limacore->em_types[24]
#define sipEnum_CtControl_CameraErrorCode              sipModuleAPI_limaadsc_limacore->em_types[24]->u.td_py_type
#define sipType_CtControl_ErrorCode              sipModuleAPI_limaadsc_limacore->em_types[25]
#define sipEnum_CtControl_ErrorCode              sipModuleAPI_limaadsc_limacore->em_types[25]->u.td_py_type
#define sipType_CtControl_ApplyPolicy              sipModuleAPI_limaadsc_limacore->em_types[23]
#define sipEnum_CtControl_ApplyPolicy              sipModuleAPI_limaadsc_limacore->em_types[23]->u.td_py_type

#define sipType_CtControl_ImageStatus              sipModuleAPI_limaadsc_limacore->em_types[26]
#define sipClass_CtControl_ImageStatus             sipModuleAPI_limaadsc_limacore->em_types[26]->u.td_wrapper_type

#define sipType_CtControl_ImageStatusCallback              sipModuleAPI_limaadsc_limacore->em_types[27]
#define sipClass_CtControl_ImageStatusCallback             sipModuleAPI_limaadsc_limacore->em_types[27]->u.td_wrapper_type

#define sipType_CtControl_Status              sipModuleAPI_limaadsc_limacore->em_types[28]
#define sipClass_CtControl_Status             sipModuleAPI_limaadsc_limacore->em_types[28]->u.td_wrapper_type

#define sipType_CtSpsImage              sipModuleAPI_limaadsc_limacore->em_types[38]
#define sipClass_CtSpsImage             sipModuleAPI_limaadsc_limacore->em_types[38]->u.td_wrapper_type

#define sipType_HeaderValue      sipModuleAPI_limaadsc_limacore->em_types[54]

#define sipType_HeaderMap      sipModuleAPI_limaadsc_limacore->em_types[53]

#define sipType_std_list_0100SoftOpRoi2Spectrum_RoiIdAndResults      sipModuleAPI_limaadsc_limacore->em_types[110]

#define sipType_std_list_0100SoftOpRoiCounter_RoiIdAndResults      sipModuleAPI_limaadsc_limacore->em_types[111]

#define sipType_std_vector_0100HwCap      sipModuleAPI_limaadsc_limacore->em_types[119]

#define sipType_std_list_0100Roi      sipModuleAPI_limaadsc_limacore->em_types[109]

#define sipType_std_list_0100VideoMode      sipModuleAPI_limaadsc_limacore->em_types[112]

#define sipType_ShutterModeList      sipModuleAPI_limaadsc_limacore->em_types[88]

#define sipType_std_list_0600std_list_3800      sipModuleAPI_limaadsc_limacore->em_types[115]

#define sipType_std_list_0100std_string      sipModuleAPI_limaadsc_limacore->em_types[116]

#define sipType_std_map_1800_0600std_list_0100std_string      sipModuleAPI_limaadsc_limacore->em_types[117]

#define sipType_std_list_1800      sipModuleAPI_limaadsc_limacore->em_types[114]

#define sipType_std_list_2400      sipModuleAPI_limaadsc_limacore->em_types[113]

#define sipType_std_vector_1800      sipModuleAPI_limaadsc_limacore->em_types[120]

#define sipType_std_vector_0100std_string      sipModuleAPI_limaadsc_limacore->em_types[121]

#define sipType_std_string      sipModuleAPI_limaadsc_limacore->em_types[118]

#define sipException_Exception sipModuleAPI_limaadsc_limacore->em_exceptions[0]
extern const sipExportedModuleDef *sipModuleAPI_limaadsc_limacore;

#endif
