MAKE_CMD1 = $(MAKE) -C software_operation
MAKE_CMD2 = $(MAKE) -C src

all:
	$(MAKE_CMD1) all
	$(MAKE_CMD2) all

clean:
	$(MAKE_CMD1) clean
	$(MAKE_CMD2) clean

depend:
	$(MAKE_CMD1) depend	
	$(MAKE_CMD2) depend