import os
try:
    Import('env')
except:
    env = Environment()

env.Program('testregex',['testregex.cpp'],CPPPATH = os.path.join('..','include'),
            LIBS=['libCommon'], LIBPATH=[os.path.join('..','src')])
