#!/usr/bin/env bash
set -x
substr=camera/
if [[ $1 == ${substr}* ]];then
	module=$(echo lima-$1|sed "s!/!-!g")
else
	module=$(echo ${1##*/})
	module=${module,,}
fi

git remote rm gitlab
git remote add gitlab git@gitlab.esrf.fr:limagroup/${module}.git
git fetch gitlab
git checkout gitlab/cmake
