import os
try:
    Import('env')
except:
    env = Environment()

env.Program('simutest',['simutest.cpp'],
            CPPPATH = [os.path.join('..','include'),
                       os.path.join('../include'),
                       os.path.join('../../common/include'),
                       os.path.join('../control/include'),
                       os.path.join('../../hardware/include'),
                       os.path.join('../../camera/simulator/include'),
                       os.path.join('../software_operation/include'),
                       os.path.join('../../third-party/Processlib/core/include')],
            LIBS=['libprocesslib','libCommon','libHardware','libControl','libSimu'],
            LIBPATH=[os.path.join('..','..','third-party','Processlib','build'),
                     os.path.join('..','..','camera','simulator','src'),
                     os.path.join('..','..','common','src'),
                     os.path.join('..','..','hardware','src'),
                     os.path.join('..','src')])
