set(KAKADU_ROOT "" CACHE PATH "Path to Kakadu root directory")
set(KAKADU_LIBRARY_DIR "" CACHE PATH "Path to Kakadu library directory")

if(DEFINED ENV{KAKADU_ROOT})
  set(KAKADU_ROOT "$ENV{KAKADU_ROOT}" CACHE PATH "Path to Kakadu root directory" FORCE)
endif()
if(DEFINED ENV{KAKADU_LIBRARY_DIR})
  set(KAKADU_LIBRARY_DIR "$ENV{KAKADU_LIBRARY_DIR}" CACHE PATH "Path to Kakadu library directory" FORCE)
endif()
if(DEFINED ENV{KAKADU_CORESYS_INCLUDE_DIR})
  set(KAKADU_CORESYS_INCLUDE_DIR "$ENV{KAKADU_CORESYS_INCLUDE_DIR}" CACHE PATH "Path to Kakadu coresys include directory" FORCE)
endif()
if(DEFINED ENV{KAKADU_SUPPORT_INCLUDE_DIR})
  set(KAKADU_SUPPORT_INCLUDE_DIR "$ENV{KAKADU_SUPPORT_INCLUDE_DIR}" CACHE PATH "Path to Kakadu support include directory" FORCE)
endif()
if(DEFINED ENV{KAKADU_AUX_LIBRARY})
  set(KAKADU_AUX_LIBRARY "$ENV{KAKADU_AUX_LIBRARY}" CACHE FILEPATH "Path to Kakadu auxiliary library" FORCE)
endif()
if(DEFINED ENV{KAKADU_CORE_LIBRARY})
  set(KAKADU_CORE_LIBRARY "$ENV{KAKADU_CORE_LIBRARY}" CACHE FILEPATH "Path to Kakadu core library" FORCE)
endif()

find_path(KAKADU_CORESYS_INCLUDE_DIR
  NAMES kdu_compressed.h
  HINTS "${KAKADU_ROOT}/coresys/common")

find_path(KAKADU_SUPPORT_INCLUDE_DIR
  NAMES kdu_stripe_compressor.h
  HINTS "${KAKADU_ROOT}/apps/support")

find_library(KAKADU_AUX_LIBRARY
  NAMES kdu_a86R
  HINTS "${KAKADU_LIBRARY_DIR}" "${KAKADU_ROOT}/lib/Linux-x86-64-gcc"
        "${KAKADU_ROOT}/lib")

find_library(KAKADU_CORE_LIBRARY
  NAMES kdu_v86R
  HINTS "${KAKADU_LIBRARY_DIR}" "${KAKADU_ROOT}/lib/Linux-x86-64-gcc"
        "${KAKADU_ROOT}/lib")

set(KAKADU_INCLUDE_DIRS ${KAKADU_CORESYS_INCLUDE_DIR} ${KAKADU_SUPPORT_INCLUDE_DIR})
set(KAKADU_LIBRARIES ${KAKADU_AUX_LIBRARY} ${KAKADU_CORE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Kakadu
  DEFAULT_MSG
  KAKADU_CORESYS_INCLUDE_DIR
  KAKADU_SUPPORT_INCLUDE_DIR
  KAKADU_AUX_LIBRARY
  KAKADU_CORE_LIBRARY)

mark_as_advanced(
  KAKADU_ROOT
  KAKADU_LIBRARY_DIR
  KAKADU_CORESYS_INCLUDE_DIR
  KAKADU_SUPPORT_INCLUDE_DIR
  KAKADU_AUX_LIBRARY
  KAKADU_CORE_LIBRARY)
