import os

try:
    Import('env')
except:
    env = Environment(CCFLAGS = '-fPIC')
    
env.Library('libCommon',Glob('*.cpp'),
            CPPPATH = [os.path.join('..','include'),os.path.join('..','..','hardware','include')])

