# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: lima-core
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - lima-sip6 13*
    - processlib 1.11*
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c 1.9*
    - hdf5 1.14*
    - libtiff
    - cbflib         # [linux]
    - openssl 3*     # [linux]
    - libnuma        # [linux]
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('lima-sip6', min_pin='x.x.x', max_pin='x') }}
    - {{ pin_compatible('processlib', max_pin='x.x') }}
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c 1.9*
    - hdf5 1.14*
    - libtiff
    - cbflib        # [linux]
    - openssl 3*    # [linux]
    - libnuma       # [linux]

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
    - h5py  # to check produced HDF5 files
  imports:
    - lima.core
  commands:
    - pytest -vs -o log_cli=true tests

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
