# Strip the 'v' from the version tag
{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG[1:] %}
{% else %}
{%   set version = "0.0.0" %}
{% endif %}

package:
  name: lima-core
  version: {{ version }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - sip 4.19* # API v12.7
    - processlib
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c >=1.9.1
    - hdf5 1.10*
    - libtiff
    - cbflib        # [linux]
    - openssl       # [linux]
    - libnuma       # [linux]
  build:
    - git
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  run:
    - python
    - {{ pin_compatible('sip', min_pin='x.x.x', max_pin='x') }}
    - {{ pin_compatible('processlib', max_pin='x.x') }}
    - libconfig 1.7*
    # I/O formats
    - zlib
    - lz4-c >=1.9.1
    - hdf5 1.10*
    - libtiff
    - cbflib        # [linux]
    - openssl       # [linux]
    - libnuma       # [linux]

test:
  imports:
    - Lima.Core
  #downstreams:
  # - lima-camera-simulator

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
